# How often the database should be updated in seconds.
refresh: 86400

# If local heads should be enabled. Only starts keeping track of joined players when enabled!
localHeads: true

# If enabled categories will require a permission to be used
# Permission: headdb.category.<category>
requireCategoryPermission: false

# If enabled, the menu will close after purchasing a head (even if the purchase fails)
closeOnPurchase: false

# Economy Options
economy:
  enable: false
  provider: "VAULT" # Supported: VAULT
  cost:
    alphabet: 100
    animals: 100
    blocks: 100
    decoration: 100
    food-drinks: 100
    humans: 100
    humanoid: 100
    miscellaneous: 100
    monsters: 100
    plants: 100

# Command Configuration
commands:
  # Commands to run ONLY if the purchase is successful.
  # They are run as CONSOLE after the player has receiver the head in their inventory.
  purchase:
    - ""

# If the original fetching fails and this is enabled,
# the plugin will attempt to fetch the heads from an archive.
# The archive is static (manually updated) so some heads may be missing, this will only be used when all else fails.
fallback: true

# Shows more plugin information in /hdb info
showAdvancedPluginInfo: true

# Debug Mode
debug: false