# When enabled heads will be fetched from startup, otherwise when the /hdb command is ran
fetchStartup: true

# When enabled, heads will be fetched async (Startup Only)
asyncStartup: false

# If the cached heads are older than these amount of seconds, the plugin will refresh the database
refresh: 3600

# Economy options
economy:
  enable: false
  cost:
    alphabet: 100
    animals: 100
    blocks: 100
    decoration: 100
    food-drinks: 100
    humans: 100
    humanoid: 100
    miscellaneous: 100
    monsters: 100
    plants: 100
    local: 1000

# Debug Mode
debug: false