# When enabled heads will be fetched from startup, otherwise when the /hdb command is ran
fetchStartup: true

# When enabled, heads will be fetched async (Startup Only)
asyncStartup: false

# If the cached heads are older than these amount of seconds, the plugin will refresh the database
refresh: 3600

# Economy options
economy:
  enable: false
  cost:
    alphabet: 100
    animals: 100
    blocks: 100
    decoration: 100
    food-drinks: 100
    humans: 100
    humanoid: 100
    miscellaneous: 100
    monsters: 100
    plants: 100
    local: 1000

# UI customization options.
ui:
  category:
    alphabet:
      location: 20
    animals:
      location: 21
    blocks:
      location: 22
    decoration:
      location: 23
    food-drinks:
      location: 24
    humans:
      location: 29
    humanoid:
      location: 30
    miscellaneous:
      location: 31
    monsters:
      location: 32
    plants:
      location: 33
    favorites:
      location: 39
    search:
      location: 40
    local:
      location: 41

# Debug Mode
debug: false
