# Economy Options
economy:
  enabled: false
  provider: "VAULT" # Supported: VAULT
  # The cost of a local (Player) head.
  localCost: 100
  # Default cost for head.
  defaultCost: 100
  # Default category cost.
  defaultCategoryCost: 100
  # Cost of categories.
  categoryCost:
    alphabet: 100
    animals: 100
    blocks: 100
    decoration: 100
    food & drinks: 100
    humans: 100
    humanoid: 100
    miscellaneous: 100
    monsters: 100
    plants: 100
  # Cost of individual heads by either number ID or texture value.
  cost:
    # The key(-2) would be the ID or TEXTURE VALUE of the head.
    # The value(0) would be the cost of the head.
    # Note that LOCAL HEADS have negative ids.
    #-2: 0

# Command Configuration. Supports PlaceholderAPI.
commands:
  # Commands to run ONLY if the purchase is successful.
  # They are run as CONSOLE after the player has received the head in their inventory.
  purchase:
    - ""

# Local Heads (from players that have joined the server)
localHeads:
  enabled: false

# Block heads from showing up in the menu.
blockedHeads:
  - ""

# If enabled categories will require a permission to be used.
# Permission: headdb.category.<category>
# Local Heads permission: headdb.category.local.* OR headdb.category.local.<PLAYER UUID>
requireCategoryPermission: false

# If the menu should show more info on the head such as: category, contributors, collections, publish date
moreInfo: true

# If the lore (ID,Tags) should be included in the inventory item given to players.
includeLore: false

# Advanced Configuration
workers:
  storage:
    threads: 1
  database:
    # Increasing this can help if you have a lot of players using the plugin at the same time.
    threads: 2