name: HeadDB
description: Database with thousands of heads

main: tsp.headdb.HeadDB
version: 2.1
api-version: 1.16
author: Silent

commands:
  headdb:
    usage: /headdb <arguments>
    description: Open the database
    aliases: [hdb, headdatabase]

permissions:
  headdb.admin:
    default: op
    children:
      headdb.open: true
      headdb.search: true
      headdb.give: true
      headdb.favorites: true
      headdb.local: true
      headdb.tagsearch: true
  headdb.open:
    default: op
  headdb.search:
    default: op
  headdb.give:
    default: op
  headdb.favorites:
    default: op
  headdb.local:
    default: op
  headdb.tagsearch:
    default: op