# noinspection YAMLSchemaValidation
name: ${project.name}
description: ${project.description}
author: TheSilentPro (Silent)

main: tsp.headdb.HeadDB
version: ${project.version}
softdepend: ["PlaceholderAPI", "Vault"]
api-version: 1.19
libraries:
  - "org.xerial:sqlite-jdbc:3.47.0.0"

spigot-id: 84967

commands:
  headdb:
    usage: /headdb help
    description: Open the database
    aliases: ["hdb", "headdatabase", "headmenu"]

permissions:
  headdb.admin:
    default: op
    children:
      headdb.command.open: true
      headdb.command.search: true
      headdb.command.give: true
      headdb.command.update: true
      headdb.command.reload: true
      headdb.command.language: true
      headdb.command.texture: true
      headdb.favorites: true
      headdb.category.local.*: true
      headdb.category.*: true
      headdb.category.all: true
  headdb.command.open:
    default: op
  headdb.command.search:
    default: op
  headdb.command.give:
    default: op
  headdb.command.update:
    default: op
  headdb.command.reload:
    default: op
  headdb.command.language:
    default: op
  headdb.command.texture:
    default: op
  headdb.favorites:
    default: op
  headdb.category.local.*:
    default: op
  headdb.category.*:
    default: op
