name: ${project.name}
description: ${project.description}

main: tsp.headdb.HeadDB
version: ${project.version}
softdepend: [Vault, Treasury]
api-version: 1.19
author: TheSilentPro (Silent)
spigot-id: 84967

buildTimestamp: ${build.timestamp}
buildAuthor: ${build.author}

# Although not up-to-date, spigot already includes gson. This is here just in case.
#libraries:
#  - "com.google.code.gson:gson:2.10"

commands:
  headdb:
    usage: /headdb help
    description: Open the database
    aliases: [hdb, headdatabase, headmenu]

permissions:
  headdb.admin:
    default: op
    children:
      headdb.command.open: true
      headdb.command.search: true
      headdb.command.give: true
      headdb.command.update: true
      headdb.favorites: true
      headdb.local: true
      headdb.category.*: true
  headdb.command.open:
    default: op
  headdb.command.search:
    default: op
  headdb.command.give:
    default: op
  headdb.command.update:
    default: op
  headdb.favorites:
    default: op
  headdb.local:
    default: op
  headdb.category.*:
    default: op