name: Publish build

on:
  push:
    branches:
      - master
      - release

jobs:
  publish:
    name: Upload build
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk
          architecture: x64

      - name: Build with Maven
        run: mvn -B package

      - name: Upload build
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: HeadDB
          releaseChannel: ${{ github.ref == 'refs/heads/release' && 'Release' || 'Dev' }}
          apiToken: ${{ secrets.BUILDS_API_TOKEN }}
          file: './target/HeadDB.jar'
          releaseNotes: ${{ github.event.head_commit.message }}